---
#title: Welcome
#hide:
#  - navigation
#  - toc
site_name: PluMCP Docs
site_url: https://plumce.com/plumcp
base_url: /plumcp
repo_url: https://github.com/plumce/plumcp
repo_name: plumce/plumcp
copyright: Copyright &copy; 2025-2026 Shantanu Kumar
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    #- navigation.indexes
    #- navigation.instant
    #- navigation.sections
    #- navigation.expand         # optional: auto-expand active section
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.footer

nav:
  - Home:
      - Home: index.md
      - Installation: installation.md
      - Quickstart: quickstart.md
      - Dependencies: dependencies.md
      - Code Navigation: navigation.md
      - What's New?: news.md
      # - MCP Server:
      #     - Server Capabilities: mcpserver/capabilities.md
      #     - Prompts: mcpserver/prompts.md
      #     - Resources: mcpserver/resources.md
      #     - Tools: mcpserver/tools.md
      #     - Advanced:
      #         - Callbacks: mcpserver/callbacks.md
      #         - OAuth: mcpserver/oauth.md
      # - MCP Client:
      #     - Client Capabilities: mcpclient/capabilities.md
      #     - Initialize: mcpclient/init.md
      #     - Request/Response: mcpclient/request.md
      #     - Advanced:
      #         - Elicitation: mcpclient/elicit.md
      #         - Sampling: mcpclient/sampling.md
      #         - OAuth: mcpclient/oauth.md
  - MCP Server:
      - MCP Server: mcpserver/index.md
      - Prompts: mcpserver/prompts.md
      - Resources: mcpserver/resources.md
      - Tools: mcpserver/tools.md
      - Utility:
          - Completion (todo): mcpserver/completion.md
          - Logging (todo): mcpserver/logging.md
      - Advanced:
          - Callbacks (todo): mcpserver/callbacks.md
          - OAuth (todo): mcpserver/oauth.md
          - Ring Adapter (todo): mcpserver/ring-adapter.md
  - MCP Client:
      - MCP Client: mcpclient/index.md
      - Roots: mcpclient/roots.md
      - Sampling: mcpclient/sampling.md
      - Elicitation: mcpclient/elicitation.md
      - Advanced:
          - OAuth: mcpclient/oauth.md

markdown_extensions:
  # for Superscript, Subscript etc.
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  #- emoji
  #- pymdownx.emoji:
  #  emoji_index: !!python/name:material.extensions.emoji.twemoji
  #  emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # for tabbed content
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  # for Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
